name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lld libffi-dev aidl autoconf automake libtool pkg-config
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Fix Sdkmanager Path for Buildozer
      run: |
        # Базовый путь к SDK на GitHub Actions
        ANDROID_HOME=/usr/local/lib/android/sdk
        
        # Создаем старую структуру папок, которую так отчаянно ищет Buildozer
        mkdir -p $ANDROID_HOME/tools/bin
        
        # Создаем фейковый скрипт sdkmanager, который внутри себя вызывает современный cmdline-tools
        echo '#!/bin/bash' > $ANDROID_HOME/tools/bin/sdkmanager
        echo '/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "$@"' >> $ANDROID_HOME/tools/bin/sdkmanager
        
        # Делаем наш скрипт-заглушку исполняемым
        chmod +x $ANDROID_HOME/tools/bin/sdkmanager
        
        echo "Fake sdkmanager successfully created at $ANDROID_HOME/tools/bin/sdkmanager"

    - name: Build with Buildozer
      run: |
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/27.3.13750724
        export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        
        # Запускаем сборку
        buildozer android debug
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
