name: Build Android APK with Action
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Заменили жесткую версию v1.2.3 на автоматическую v1
    - name: Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
